# Use the official PHP image with Apache
FROM php:8.1-apache

# Install system dependencies and PHP extensions
# this use mySQL, if you want to use PostgreSQL, replace libpq-dev and pdo_mysql with libpq-dev and pdo_pgsql
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    libzip-dev \
    zip \
    git \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd pdo pdo_mysql zip \
    && a2enmod rewrite

# Set working directory inside the container
WORKDIR /var/www/html

# Copy Laravel project files into the container
COPY . /var/www/html

# Set correct permissions (important for Laravel)
# if this does not work, you might need to connect to the container and run these commands manually
# docker exec -it your-container-name or id bash , then run the commands below
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Expose Apache port
EXPOSE 80

# Run Apache in the foreground
CMD ["apache2-foreground"]
